version: '3.10'

networks:
  globalnetwork:
    driver: bridge

services:
    postgres:
        networks:
          - globalnetwork
        image: postgres:15
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=luxonis
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - db-data:/var/lib/postgresql/data
 
    app:
        networks:
          - globalnetwork
        depends_on:
          - postgres
        build: .
        ports:
          - "8080:8080"


volumes:
  db-data:
      driver: local
